# F-Droid build metadata for Podometer.
# See https://f-droid.org/docs/Build_Metadata_Reference/ for full reference.

Categories:
  - Sports & Health

License: GPL-3.0-or-later

SourceCode: https://github.com/JanJetze/podometer
IssueTracker: https://github.com/JanJetze/podometer/issues

Liberapay: JanJetze

Name: Podometer
AutoName: Podometer

RepoType: git
Repo: https://github.com/JanJetze/podometer.git

Builds:
  - versionName: 1.0.0
    versionCode: 1
    commit: v1.0.0
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.0.0
CurrentVersionCode: 1
