// SPDX-License-Identifier: GPL-3.0-or-later
package com.podometer.data

import com.podometer.data.db.DailySummary
import com.podometer.data.db.StepBucket
import com.podometer.data.db.StepBucketDao
import com.podometer.data.db.StepDao
import com.podometer.util.DateTimeUtils
import java.time.LocalDate
import javax.inject.Inject
import javax.inject.Singleton
import kotlin.random.Random

/**
 * Generates realistic test data for all views (Dashboard, Trends, Settings).
 *
 * When the "Use test data" developer toggle is enabled, this class seeds the
 * database with 60 days of daily summaries and today's 5-minute step buckets.
 * When the toggle is disabled, test data is removed while preserving any real
 * tracking data that was recorded while the toggle was off.
 *
 * Test data is distinguishable by date range: it covers the 60 days ending
 * yesterday plus a partial "today" that merges with live tracking.
 */
@Singleton
class TestDataGenerator @Inject constructor(
    private val stepDao: StepDao,
    private val stepBucketDao: StepBucketDao,
) {

    companion object {
        /** Number of historical days to generate (excluding today). */
        private const val HISTORY_DAYS = 60

        /** Stride length in km used for distance calculation. */
        private const val STRIDE_KM = 0.00075f

        /** 5-minute bucket duration in milliseconds. */
        private const val BUCKET_MS = 5L * 60 * 1000

        /** Seed for reproducible test data so toggling off/on yields the same set. */
        private const val SEED = 42L

        /**
         * Marker prefix for test-data dates. We use this to identify which
         * daily summaries were generated by us.
         */
        private val TEST_DATA_DATES = mutableSetOf<String>()
    }

    /**
     * Seeds the database with test data.
     *
     * Generates:
     * - 60 days of [DailySummary] rows with varied step counts (3,000–14,000)
     *   to exercise all goal tiers and streak logic.
     * - Today's [StepBucket] entries (5-minute buckets from 6 AM to current hour)
     *   to populate the Dashboard "Today's Steps" chart.
     *
     * Uses a fixed [Random] seed so the data is reproducible.
     */
    suspend fun seed() {
        val random = Random(SEED)
        val today = LocalDate.now()

        // ── Historical daily summaries (yesterday back 60 days) ──────────────
        val summaries = mutableListOf<DailySummary>()
        for (dayOffset in HISTORY_DAYS downTo 1) {
            val date = today.minusDays(dayOffset.toLong())
            val steps = generateDaySteps(random, date)
            val distance = steps * STRIDE_KM
            summaries.add(
                DailySummary(
                    date = date.toString(),
                    totalSteps = steps,
                    totalDistance = distance,
                )
            )
        }

        // ── Today's summary ──────────────────────────────────────────────────
        val todaySteps = generateDaySteps(random, today)
        val todayDistance = todaySteps * STRIDE_KM
        summaries.add(
            DailySummary(
                date = today.toString(),
                totalSteps = todaySteps,
                totalDistance = todayDistance,
            )
        )

        // Track which dates we're inserting
        TEST_DATA_DATES.clear()
        summaries.forEach { TEST_DATA_DATES.add(it.date) }

        stepDao.insertAllDailySummaries(summaries)

        // ── Today's 5-minute buckets ─────────────────────────────────────────
        val todayStartMs = DateTimeUtils.startOfDayMillis(today)
        val sixAmMs = todayStartMs + 6L * 60 * 60 * 1000  // 6:00 AM
        val nowMs = System.currentTimeMillis()
        val bucketsEndMs = minOf(nowMs, todayStartMs + 22L * 60 * 60 * 1000) // cap at 10 PM

        val bucketRandom = Random(SEED + 1)
        var bucketTimestamp = DateTimeUtils.truncateToBucket(sixAmMs)
        var remainingSteps = todaySteps

        // Count total buckets first to distribute steps
        val totalBuckets = ((bucketsEndMs - bucketTimestamp) / BUCKET_MS).toInt().coerceAtLeast(1)
        val baseStepsPerBucket = remainingSteps / totalBuckets

        var bucketIndex = 0
        while (bucketTimestamp < bucketsEndMs) {
            // Vary each bucket ±40% around base, with realistic patterns:
            // fewer steps early morning, more mid-morning and afternoon
            val hourOfDay = ((bucketTimestamp - todayStartMs) / (60 * 60 * 1000)).toInt()
            val activityMultiplier = when (hourOfDay) {
                in 6..7 -> 0.4f   // early morning - light
                in 8..9 -> 1.2f   // morning commute
                in 10..11 -> 0.8f // mid-morning
                in 12..13 -> 1.3f // lunch walk
                in 14..16 -> 0.6f // afternoon desk
                in 17..18 -> 1.4f // evening commute/walk
                in 19..20 -> 0.9f // evening
                else -> 0.3f      // early/late
            }
            val variance = 0.6f + bucketRandom.nextFloat() * 0.8f // 0.6–1.4
            val bucketSteps = (baseStepsPerBucket * activityMultiplier * variance).toInt()
                .coerceAtLeast(0)

            stepBucketDao.upsert(
                StepBucket(
                    timestamp = bucketTimestamp,
                    stepCount = bucketSteps,
                )
            )

            bucketTimestamp += BUCKET_MS
            bucketIndex++
        }
    }

    /**
     * Removes test data from the database.
     *
     * Deletes the daily summaries that were inserted by [seed] and clears
     * today's step buckets (since they were test-generated).
     */
    suspend fun clear() {
        // Remove historical test summaries by re-generating the same date set
        val today = LocalDate.now()
        for (dayOffset in HISTORY_DAYS downTo 0) {
            val date = today.minusDays(dayOffset.toLong()).toString()
            // Upsert with 0 steps effectively "clears" the test data.
            // We delete by upserting zeros so the Flow triggers a UI update.
            stepDao.upsertStepsAndDistance(date, 0, 0f)
        }

        // Clear all step buckets (test data only populated today's buckets)
        stepBucketDao.deleteAll()
    }

    /**
     * Generates a realistic step count for a given day.
     *
     * Returns values distributed across all three goal tiers:
     * - ~20% of days: below minimum (2,000–4,999) — bad days
     * - ~30% of days: minimum to target (5,000–7,999) — okay days
     * - ~35% of days: target to stretch (8,000–11,999) — good days
     * - ~15% of days: above stretch (12,000–15,000) — great days
     *
     * Weekends tend to be slightly lower.
     */
    private fun generateDaySteps(random: Random, date: LocalDate): Int {
        val isWeekend = date.dayOfWeek.value >= 6
        val roll = random.nextFloat()

        val baseSteps = when {
            roll < 0.20f -> random.nextInt(2_000, 5_000)  // below minimum
            roll < 0.50f -> random.nextInt(5_000, 8_000)  // minimum–target
            roll < 0.85f -> random.nextInt(8_000, 12_000) // target–stretch
            else -> random.nextInt(12_000, 15_001)         // above stretch
        }

        return if (isWeekend) (baseSteps * 0.8f).toInt() else baseSteps
    }
}
